version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile-Flask
    ports:
      - "5000:5000"

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile-FastAPI
    ports:
      - "8000:8000"
